# Example configurations for Wololo Wake-on-LAN

# Configuration 1: Fast sync (every 15 seconds)
server:
  ip: "0.0.0.0"
  port: 3000
  external_url: "http://localhost:3000"

sync:
  enabled: true
  interval_seconds: 15 # Fast refresh for development/testing

devices:
  - name: "Gaming PC"
    mac_address: "AA:BB:CC:DD:EE:FF"
    ip_address: "192.168.29.185"
