server:
  ip: "0.0.0.0"
  port: 3000
  external_url: "http://localhost:3000"

sync:
  enabled: true
  interval_seconds: 15 # Auto-refresh device status every 15 seconds

devices:
  - name: "Gaming PC"
    mac_address: "AA:BB:CC:DD:EE:FF"
    ip_address: "192.168.1.100"
  # - name: "Device-172.18.0.1"  # No MAC address found
  #   mac_address: "XX:XX:XX:XX:XX:XX"
  #   ip_address: "172.18.0.1"
  # - name: "Device-172.19.0.1"  # No MAC address found
  #   mac_address: "XX:XX:XX:XX:XX:XX"
  #   ip_address: "172.19.0.1"
  - name: "Device-172.19.0.2"
    mac_address: "42:ab:8a:a1:ab:d6"
    ip_address: "172.19.0.2"
  - name: "Device-192.168.29.1"
    mac_address: "8c:a3:99:e1:18:bd"
    ip_address: "192.168.29.1"
  - name: "pi.hole"
    mac_address: "b8:27:eb:20:2c:bf"
    ip_address: "192.168.29.66"
  - name: "Mac.local"
    mac_address: "16:7b:32:f1:c2:3c"
    ip_address: "192.168.29.113"
  # - name: "jd.sharmashobh.it"  # No MAC address found
  #   mac_address: "XX:XX:XX:XX:XX:XX"
  #   ip_address: "192.168.29.185"
  - name: "SetTopBox-0810.local"
    mac_address: "10:76:36:af:da:83"
    ip_address: "192.168.29.207"
  - name: "flaresolverr.sharmashobh.it"
    mac_address: "18:66:da:00:f1:12"
    ip_address: "192.168.29.223"
  - name: "storage.sharmashobh.it"
    mac_address: "dc:a6:32:c4:d8:e2"
    ip_address: "192.168.29.224"
  - name: "nocodb.sharmashobh.it"
    mac_address: "dc:a6:32:fd:01:f2"
    ip_address: "192.168.29.225"
  - name: "k3struenas01.local"
    mac_address: "00:a0:98:1f:95:43"
    ip_address: "192.168.29.228"
  - name: "RE200.local"
    mac_address: "da:62:79:4d:4e:75"
    ip_address: "192.168.29.230"
  - name: "MacBookPro.local"
    mac_address: "ca:68:c8:2c:15:76"
    ip_address: "192.168.29.231"
  - name: "ESP_3901E0.local"
    mac_address: "da:62:79:4d:4e:75"
    ip_address: "192.168.29.251"
  # - name: "Device-172.17.0.1"  # No MAC address found
  #   mac_address: "XX:XX:XX:XX:XX:XX"
  #   ip_address: "172.17.0.1"
  # - name: "tower-pc.tail668401.ts.net"  # No MAC address found
  #   mac_address: "XX:XX:XX:XX:XX:XX"
  #   ip_address: "100.78.37.79"
  # - name: "Device-172.28.10.1"  # No MAC address found
  #   mac_address: "XX:XX:XX:XX:XX:XX"
  #   ip_address: "172.28.10.1"
  - name: "Device-172.28.10.2"
    mac_address: "72:0b:1d:ce:1a:c4"
    ip_address: "172.28.10.2"
  - name: "Device-172.28.10.3"
    mac_address: "72:c7:31:17:2a:61"
    ip_address: "172.28.10.3"
